//! WGSL generation: one multi-entry-point module per world.
//!
//! `generate_wgsl` validates the IR, checks schedule conflicts and emits a
//! single WGSL source containing:
//!
//! - struct definitions shared with the CPU (`QueryRange`, `StructuralCommand`,
//!   `RenderInstance`);
//! - group 0 storage bindings (entity table, sorting buffers, command buffer
//!   and three buffers per component: data / current version / baseline);
//! - group 1 uniform resources plus the RenderData instance buffer;
//! - per-query pass predicates and the three sorting entry points;
//! - one `system_*` compute entry point per system.

pub mod bind_layout;
mod sorting;
mod system_emit;
mod validation;
pub mod wgsl_types;

pub use bind_layout::{QueryRange, RenderInstance, StructuralCommand};
pub use validation::{check_limits, check_schedule_conflicts, required_group0_bindings};

use crate::ir::{ComponentType, EcsIr};
use crate::EcsError;
use system_emit::EmitCtx;

/// Entry point names reserved for the sorting pass.
const RESERVED_ENTRY_POINTS: [&str; 3] = ["system_prep_count", "system_prep_scan", "system_prep_fill"];

/// Generate the complete WGSL module for a validated world.
pub fn generate_wgsl(ir: &EcsIr) -> Result<String, EcsError> {
    ir.validate()?;
    check_schedule_conflicts(ir)?;

    for system in &ir.systems {
        let entry = format!("system_{}", system.name);
        if RESERVED_ENTRY_POINTS.contains(&entry.as_str()) {
            return Err(EcsError::WgslInvalid(format!(
                "system name '{}' collides with the reserved sorting entry point {entry}",
                system.name
            )));
        }
    }

    let mut out = String::new();
    out.push_str("// Generated by neon-gpu-ecs. Do not edit.\n\n");

    emit_structs(&mut out);
    emit_bindings(&mut out, ir);
    for index in 0..ir.queries.len() {
        out.push_str(&sorting::emit_query_predicate(ir, index));
        out.push('\n');
    }
    out.push_str(&sorting::emit_sorting(ir));
    out.push('\n');

    for system in &ir.systems {
        let ctx = EmitCtx {
            ir,
            slot: system.query_id,
            system_id: system.id,
        };
        out.push_str(&system_emit::emit_system(system, &ctx)?);
        out.push('\n');
    }

    Ok(out)
}

fn emit_structs(out: &mut String) {
    out.push_str("struct QueryRange {\n    start : u32,\n    count : u32,\n}\n\n");
    out.push_str(
        "struct StructuralCommand {\n    kind : u32,\n    a : u32,\n    b : u32,\n    reserved : u32,\n}\n\n",
    );
    out.push_str(
        "struct RenderInstance {\n    transform : vec4f,\n    color : vec4f,\n}\n\n",
    );
}

fn emit_bindings(out: &mut String, ir: &EcsIr) {
    use bind_layout::*;

    out.push_str(&format!(
        "@group(0) @binding({ENTITY_ACTIVE_BINDING}) var<storage, read_write> entityActive : array<u32>;\n"
    ));
    out.push_str(&format!(
        "@group(0) @binding({QUERY_COUNTS_BINDING}) var<storage, read_write> queryCounts : array<atomic<u32>>;\n"
    ));
    out.push_str(&format!(
        "@group(0) @binding({QUERY_CURSORS_BINDING}) var<storage, read_write> queryCursors : array<atomic<u32>>;\n"
    ));
    out.push_str(&format!(
        "@group(0) @binding({FRAME_PREP_BINDING}) var<storage, read_write> framePrepBuffer : array<QueryRange>;\n"
    ));
    out.push_str(&format!(
        "@group(0) @binding({COMPACTED_IDS_BINDING}) var<storage, read_write> compactedEntityIds : array<u32>;\n"
    ));
    out.push_str(&format!(
        "@group(0) @binding({INDIRECT_ARGS_BINDING}) var<storage, read_write> indirectArgs : array<vec3u>;\n"
    ));
    out.push_str(&format!(
        "@group(0) @binding({COMMAND_BUFFER_BINDING}) var<storage, read_write> commandBuffer : array<StructuralCommand>;\n"
    ));
    out.push_str(&format!(
        "@group(0) @binding({COMMAND_COUNT_BINDING}) var<storage, read_write> commandCount : atomic<u32>;\n"
    ));

    for comp in &ir.components {
        let id = comp.id;
        let data_binding = component_data_binding(id);
        let version_binding = component_version_binding(id);
        let baseline_binding = component_baseline_binding(id);
        let data_type = match comp.ty {
            // Atomic RMW components use atomic storage.
            ComponentType::U32 => "array<atomic<u32>>".to_string(),
            ComponentType::I32 => "array<atomic<i32>>".to_string(),
            other => format!("array<{}>", other.wgsl_storage_type()),
        };
        out.push_str(&format!(
            "@group(0) @binding({data_binding}) var<storage, read_write> ecs_c{id} : {data_type};\n"
        ));
        out.push_str(&format!(
            "@group(0) @binding({version_binding}) var<storage, read_write> ecs_cv{id} : array<atomic<u32>>;\n"
        ));
        out.push_str(&format!(
            "@group(0) @binding({baseline_binding}) var<storage, read_write> ecs_cb{id} : array<atomic<u32>>;\n"
        ));
    }

    for res in &ir.resources {
        out.push_str(&format!(
            "@group(1) @binding({}) var<uniform> ecs_r{} : {};\n",
            res.binding_slot,
            res.id,
            res.ty.wgsl_storage_type()
        ));
    }
    out.push_str(&format!(
        "@group(1) @binding({}) var<storage, read_write> renderInstances : array<RenderInstance>;\n",
        bind_layout::RENDER_INSTANCES_BINDING
    ));
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reserved_entry_point_names_are_rejected() {
        let mut ir = crate::tests_support::physics_world();
        ir.systems[0].name = "prep_count".to_string();
        let err = generate_wgsl(&ir).unwrap_err();
        assert!(matches!(err, EcsError::WgslInvalid(_)));
    }
}
