[workspace]
members = [
    "crates/neon-protocol",
    "crates/neon-ipc",
    "crates/neon-observability",
    "crates/neon-world-bridge",
    "crates/neon-projectd",
    "crates/neon-eventd",
    "crates/neon-ui-schema",
    "crates/neon-wgpu-runtime",
    "crates/neon-wgpu-ai",
    "crates/neon-gpu-ecs",
    "crates/neon-ui-runtime",
    "crates/neon-ui",
    "crates/neon-cli",
    "crates/neon-dev",
    "crates/neon-android-host",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
version = "0.2.7"
repository = "https://github.com/unco999/Neon3-CiJian"
homepage = "https://github.com/unco999/Neon3-CiJian"
rust-version = "1.85"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bytemuck = { version = "1.24", features = ["derive"] }
pollster = "0.4"
wgpu = "30.0"
winit = "0.30"
fontdue = "0.9"
 windows = { version = "0.62.2", features = ["Foundation", "Foundation_Numerics", "Graphics", "Graphics_Capture", "Graphics_DirectX", "Graphics_DirectX_Direct3D11", "Win32_Foundation", "Win32_Graphics_Direct2D", "Win32_Graphics_Direct2D_Common", "Win32_Graphics_Direct3D11", "Win32_Graphics_Direct3D11on12", "Win32_Graphics_Direct3D12", "Win32_Graphics_DirectComposition", "Win32_Graphics_Dxgi", "Win32_Graphics_Dxgi_Common", "Win32_Graphics_Dwm", "Win32_Graphics_Gdi", "Win32_System_Com", "Win32_System_LibraryLoader", "Win32_System_Threading", "Win32_UI_Controls_Dialogs", "Win32_UI_WindowsAndMessaging", "Win32_System_WinRT_Composition", "Win32_System_WinRT_Graphics_Direct2D", "UI_Composition", "UI_Composition_Desktop", "Graphics_Effects", "System"] }
windows-derive = "0.2"
windows-sys = { version = "0.59", features = ["Win32_Foundation", "Win32_Security", "Win32_System_JobObjects", "Win32_System_Threading"] }
